### PR TITLE
Fix small code problems

### LINKED ISSUE #30: [PATCH] Simple fixes of some small problem code
<pre>=== This issue was migrated from JIRA ===
Type: Task
Priority: Major
Status: Open
Resolution: UNRESOLVED
Reported by: dbrosius
Assigned to: ROME Jira Lead
Created: Sun Feb 12 06:38:33 CET 2006
Updated: Thu Sep 15 20:55:29 CEST 2011
Resolved: Sun Feb 12 06:39:20 CET 2006
Version: current
Fix version: milestone 1
JIRA Link: <a href="https://rometools.jira.com/browse/ROME-29">https://rometools.jira.com/browse/ROME-29</a>
=========================================</pre>
<p>Fixes for <br class="atl-forced-newline" />  – implementation of clone()<br class="atl-forced-newline" />  – better map iterating<br class="atl-forced-newline" />  – unnecessary toString calls<br class="atl-forced-newline" />  – making sure streams are closed<br class="atl-forced-newline" />  – removal of non&#45;shortcircuiting boolean logic<br class="atl-forced-newline" /> etc.</p>

### PR DESCRIPTION
**Pull request by mishako**
Fixes #30
This are the changes from a 10-year-old patch. I left out changes to the `clone()` methods, because Java cloning is considered broken anyway.

### CODE REVIEW

**Comment by mishako** [comment]
@PatrickGotthard @snoopdave

**Comment by mishako** [comment]
Any thoughts?

File: src/main/java/com/rometools/rome/io/WireFeedInput.java [hunk 1]
```diff
@@ -204,11 +204,14 @@ public void setAllowDoctypes(boolean allowDoctypes) {
...
+            if (xmlHealerOn) {
+                reader = new XmlFixerReader(reader);
+            }
+            feed = this.build(reader);
+        } finally {
+            reader.close();
         }
-        feed = this.build(reader);
-        reader.close();
         return feed;
```
Comment (PatrickGotthard) [inline src/main/java/com/rometools/rome/io/WireFeedInput.java]: Does this compile? feed may not have been initialized

**Comment by PatrickGotthard** [comment]
Hi mishako,

everything except the commented code looks good.

Regards,
Patrick
